#!/bin/bash
#
# Determine what $1. If it's a file, edit it. If it's a directory, cd to it

[ -z $1 ] && exit 6

[ -f $1 ] && vi $1 && exit

[ -d $1 ] && cd $1 && exec bash

echo not a file or directory
