#!/bin/bash

# needs further development
# trap can be configured to execute a command when receiving a signal
# see man 7 signal for available signals
# inspired by mitch frazier in Linux Journal august 7, 2019
# example: run trap on exit signal

tempfile=/tmp/tmpdata
touch $tempfile
ls -l $tempfile
trap "rm -f $tempfile" EXIT

# example2: ignore Ctrl-C - needs optimization doesn't work now
ctrlc_count=0

function no_ctrlc()
{
	let ctrlc_count++
	echo
	if [[ $ctrlc_count == 1 ]]; then
		echo "Don\'t do that." 
	elif [[ $ctrlc_count == 2 ]]; then
		echo "if you\'re sure, do it once more." 
	else
		echo "Okay, bye."
		exit
	fi
}

# define the trap that reacts on ctrl-c
trap no_ctrlc SIGINT

# run the command on something that will be restarted after receiving SIGINT
# this fails if you do it on while sleep 10000
while true
do
	echo doing nothing for a long time
	sleep 10000
done
