#!/bin/bash

#
#
#

if [ -z $1 ]
then
	echo tes bete
	exit 1
elif [ ! -e $1 ]
then
	echo nimporte quoi
	exit 2
elif [ -d $1 ]
then
	echo oui, cest un repertoire
# si cest un fichier, regarder si executable ou bash ou nimporte quoi 
elif [ ! -f $1 ]
then
	echo fichier bizarre
elif [ -x $1 ]
then
	echo il est executable
elif grep '#!/bin/bash' $1 
then
	echo cest du bash
	chmod +x $1
else
	echo cest du nimporte quoi
fi	
