#!/bin/bash
#
# Display users that are member of a group.
# Group name has to be provided as an argument

[ -z $1 ] && echo you must provide a group name && exit 1

# get group ID for $1

GID=`grep ^$1: /etc/group | cut -d : -f3`
echo GID is $GID

# get users that have $1 as their primary group and store
# that in variable USERS

for i in `cat /etc/passwd`
do
	grep $GID $i && cut -d : -f1 $i >> /tmp/userlist
done

cat /tmp/userlist
